routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::group(['middleware' => ['auth']], function()
{
    Route::get('/', 'HomeController@index')->name('home');

    Route::resource('wallet', 'WalletController', [
        'except' => ['index']
    ]);

    Route::resource('transaction', 'TransactionController', [
        'except' => ['index', 'edit']
    ]);
});

Auth::routes();

app/Models/Transaction.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\BelongsTo;
use Illuminate\Database\Eloquent\SoftDeletes;

/**
 * Class Transaction
 *
 * @package App\Models
 * @author Sergei Randin svr@svr.lv
 */
class Transaction extends Model
{
    use SoftDeletes;

    /**
     * Fillable fields
     *
     * @var array
     */
    protected $fillable = [
        'wallet_from',
        'wallet_to',
        'amount',
        'reference'
    ];

    /**
     * Get the hidden attributes for the model.
     *
     * @return array
     */
    public function getHidden()
    {
        return [
            'updated_at',
            'created_at',
            'deleted_at',
        ];
    }

    /**
     * Wallet relationships for deposits
     *
     * @return BelongsTo
     */
    public function from()
    {
        return $this->belongsTo(Wallet::class, 'wallet_from');
    }


    /**
     * Wallet relationships for withdrawals
     *
     * @return BelongsTo
     */
    public function to()
    {
        return $this->belongsTo(Wallet::class, 'wallet_to');
    }
}

app/Models/User.php
<?php

namespace App\Models;

use Illuminate\Auth\Authenticatable;
use Illuminate\Contracts\Auth\Access\Authorizable as AuthorizableContract;
use Illuminate\Contracts\Auth\Authenticatable as AuthenticatableContract;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Foundation\Auth\Access\Authorizable;

/**
 * Class User
 *
 * @package App\Models
 * @author Sergei Randin svr@svr.lv
 */
class User extends Model implements AuthenticatableContract, AuthorizableContract
{
    use Authenticatable, Authorizable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name',
        'email',
        'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password',
        'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
}

app/Models/Wallet.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

/**
 * Class Wallet
 *
 * @package App\Models
 * @author Sergei Randin svr@svr.lv
 */
class Wallet extends Model
{
    use SoftDeletes;

    /**
     * Fillable fields
     *
     * @var array
     */
    protected $fillable = [
        'name',
        'user_id'
    ];

    /**
     * Get the hidden attributes for the model.
     *
     * @return array
     */
    public function getHidden()
    {
        return [
            'updated_at',
            'created_at',
            'deleted_at',
        ];
    }

    /**
     * Get the deposits for the wallet.
     */
    public function deposits()
    {
        return $this->hasMany(Transaction::class, 'wallet_to');
    }

    /**
     * Get the withdrawals for the wallet.
     */
    public function withdrawals()
    {
        return $this->hasMany(Transaction::class, 'wallet_from');
    }

    public function user()
    {
        return $this->belongsTo(User::class);
    }
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Auth\Access\AuthorizesRequests;
use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Routing\Controller as BaseController;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/HomeController.php
<?php

namespace App\Http\Controllers;

use App\Repositories\WalletRepositoryInterface;
use Illuminate\Contracts\Support\Renderable;

/**
 * Class HomeController
 *
 * @package App\Http\Controllers
 * @author Sergei Randin svr@svr.lv
 */
class HomeController extends Controller
{
    private $walletRepository;

    /**
     * Home controller constructor
     *
     * @param $walletRepository
     */
    public function __construct(WalletRepositoryInterface $walletRepository)
    {
        $this->walletRepository = $walletRepository;
    }

    /**
     * Show the application dashboard.
     *
     * @return Renderable
     */

    public function index()
    {
        $wallets = $this->walletRepository->getUserWallets();

        return view('home', compact('wallets'));
    }
}

app/Http/Controllers/TransactionController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\FraudulentTransactionRequest;
use App\Http\Requests\TransactionRequest;
use App\Facades\Cashier;

/**
 * Class TransactionController
 *
 * @package App\Http\Controllers
 * @author Sergei Randin svr@svr.lv
 */
class TransactionController extends Controller
{
    private $transactionRepository;
    private $walletRepository;

    /**
     * Transaction controller constructor
     */
    public function __construct()
    {
        $this->transactionRepository = Cashier::getTransactionRepository();
        $this->walletRepository = Cashier::getWalletRepository();
    }

    public function create()
    {
        $fromWallets = $this->walletRepository->getUserWallets();
        $allWallets = $this->walletRepository->all();

        return view('transactions.create', compact(['fromWallets', 'allWallets']));
    }

    public function store(TransactionRequest $request)
    {
        $this->transactionRepository->create($request);

        return redirect()->back()->with('status', 'Transaction has been added');
    }

    public function update(FraudulentTransactionRequest $request, $id)
    {
        $this->transactionRepository->markFraudulent($id, $request);

        return redirect()->back()->with('status', 'Transaction marked fraudulent');
    }

    public function destroy($id)
    {
        $this->transactionRepository->delete($id);

        return redirect()->back()->with('status', 'Transaction has been deleted');
    }
}

app/Http/Controllers/WalletController.php
<?php

namespace App\Http\Controllers;

use App\Facades\Cashier;
use App\Http\Requests\WalletRequest;

/**
 * Class WalletController
 *
 * @package App\Http\Controllers
 * @author Sergei Randin svr@svr.lv
 */
class WalletController extends Controller
{
    protected $walletRepository;

    /**
     * Wallet controller constructor
     */
    public function __construct()
    {
        $this->walletRepository = Cashier::getWalletRepository();
    }

    public function create()
    {
        return view('wallets.create');
    }

    public function store(WalletRequest $request)
    {
        $this->walletRepository->create($request);

        return redirect()->back()->with('status', 'Wallet has been added');
    }

    public function edit($id)
    {
        $wallet = $this->walletRepository->get($id);

        return view('wallets.edit', compact('wallet'));
    }

    public function update(WalletRequest $request, $id)
    {
        $this->walletRepository->update($id, $request);

        return redirect()->back()->with('status', 'Wallet has been renamed');
    }

    public function show($id)
    {
        $wallet = Cashier::prepareSums($id);

        return view('wallets.show', compact('wallet'));
    }

    public function destroy($id)
    {
        $this->walletRepository->delete($id);

        return redirect()->back()->with('status', 'Wallet has been deleted');
    }
}

resources/views/home.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">{{ __('Dashboard') }}</div>

                <div class="card-body">
                    @if (session('status'))
                        <div class="alert alert-success" role="alert">
                            {{ session('status') }}
                        </div>
                    @endif

                    <h3>Your wallets <a href="{{ route('wallet.create') }}" class="label label-default">{{ __('Add new') }}</a></h3>

                    <ul class="list-group">
                    @forelse($wallets as $wallet)
                            <li class="list-group-item">
                                <h3 class="text-center">
                                    <a href="{{ route('wallet.show', $wallet->id) }}">{{ $wallet->name }}</a>
                                </h3>
                                <hr />
                                <div class="btn-group" role="group" aria-label="...">
                                    <a class="btn btn-primary" href="{{ route('wallet.edit', $wallet->id) }}">{{ __('Rename') }}</a>
                                    <form action="{{ route('wallet.destroy', $wallet->id)}}" method="post">
                                        @csrf
                                        @method('DELETE')
                                        <button class="btn btn-danger" type="submit">{{ __('Delete') }}</button>
                                    </form>
                                </div>
                            </li>
                    @empty
                            <li class="list-group-item">You have no wallets, please create one</li>
                    @endforelse
                    </ul>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/layouts/app.blade.php
<!doctype html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>{{ config('app.name', 'Laravel') }}</title>

    <!-- Scripts -->
    <script src="{{ asset('js/app.js') }}" defer></script>

    <!-- Fonts -->
    <link rel="dns-prefetch" href="//fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css?family=Nunito" rel="stylesheet">

    <!-- Styles -->
    <link href="{{ asset('css/app.css') }}" rel="stylesheet">
</head>
<body>
    <div id="app">
        <nav class="navbar navbar-expand-md navbar-light bg-white shadow-sm">
            <div class="container">
                <a class="navbar-brand" href="{{ url('/') }}">
                    {{ config('app.name', 'Laravel') }}
                </a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="{{ __('Toggle navigation') }}">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <!-- Left Side Of Navbar -->
                    <ul class="navbar-nav mr-auto">

                    </ul>

                    <!-- Right Side Of Navbar -->
                    <ul class="navbar-nav ml-auto">
                        <!-- Authentication Links -->
                        @guest
                            <li class="nav-item">
                                <a class="nav-link" href="{{ route('login') }}">{{ __('Login') }}</a>
                            </li>
                            @if (Route::has('register'))
                                <li class="nav-item">
                                    <a class="nav-link" href="{{ route('register') }}">{{ __('Register') }}</a>
                                </li>
                            @endif
                        @else
                            <li class="nav-item dropdown">
                                <a id="navbarDropdown" class="nav-link dropdown-toggle" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" v-pre>
                                    {{ Auth::user()->name }} <span class="caret"></span>
                                </a>

                                <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                                    <a class="dropdown-item" href="{{ route('logout') }}"
                                       onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">
                                        {{ __('Logout') }}
                                    </a>

                                    <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                                        @csrf
                                    </form>
                                </div>
                            </li>
                        @endguest
                    </ul>
                </div>
            </div>
        </nav>

        <main class="py-4">
            @yield('content')
        </main>
    </div>
</body>
</html>

resources/views/transactions/create.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-8">
                <div class="card">
                    <div class="card-header">{{ __('Create new Transaction') }}</div>

                    <div class="card-body">
                        @if (session('status'))
                            <div class="alert alert-success" role="alert">
                                {{ session('status') }}
                            </div>
                        @endif
                        <form method="POST" action="{{ route('transaction.store') }}">
                            @csrf
                            <div class="form-group row">
                                <label for="from_wallet" class="col-md-4 col-form-label text-md-right">{{ __('From') }}</label>
                                <div class="col-md-6">
                                    <select class="form-control @error('from_wallet') is-invalid @enderror" id="from_wallet" name="from_wallet" required>
                                        <option>Choose wallet</option>
                                        @forelse($fromWallets as $fromWallet)
                                        <option value="{{ $fromWallet->id }}">{{ $fromWallet->name }}</option>
                                        @empty

                                        @endforelse
                                    </select>
                                    @error('from_wallet')
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                    @enderror
                                </div>

                                <label for="to_wallet" class="col-md-4 col-form-label text-md-right">{{ __('To') }}</label>
                                <div class="col-md-6">
                                    <select class="form-control @error('to_wallet') is-invalid @enderror" id="to_wallet" name="to_wallet" required>
                                        <option>Choose wallet</option>
                                        @forelse($allWallets as $allWallet)
                                            <option value="{{ $allWallet->id }}">{{ $allWallet->name }}</option>
                                        @empty

                                        @endforelse
                                    </select>
                                    @error('to_wallet')
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                    @enderror
                                </div>

                                <label for="from_wallet" class="col-md-4 col-form-label text-md-right">{{ __('Amount') }}</label>
                                <div class="col-md-6">
                                    <input id="amount" type="number" class="form-control @error('amount') is-invalid @enderror" name="amount" value="{{ old('amount') }}" required autocomplete="amount" autofocus>
                                    @error('amount')
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                    @enderror
                                </div>

                                <label for="from_wallet" class="col-md-4 col-form-label text-md-right">{{ __('Reference') }}</label>
                                <div class="col-md-6">
                                    <input id="reference" type="text" class="form-control @error('reference') is-invalid @enderror" name="reference" value="{{ old('reference') }}" required autocomplete="reference" autofocus>
                                    @error('reference')
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                    @enderror
                                </div>
                            </div>

                            <div class="form-group row mb-0">
                                <div class="col-md-6 offset-md-4">
                                    <button type="submit" class="btn btn-primary">
                                        {{ __('Create') }}
                                    </button>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/wallets/create.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-8">
                <div class="card">
                    <div class="card-header">{{ __('Create new Wallet') }}</div>

                    <div class="card-body">
                        @if (session('status'))
                            <div class="alert alert-success" role="alert">
                                {{ session('status') }}
                            </div>
                        @endif
                        <form method="POST" action="{{ route('wallet.store') }}">
                            @csrf
                            <div class="form-group row">
                                <label for="name" class="col-md-4 col-form-label text-md-right">{{ __('Name') }}</label>

                                <div class="col-md-6">
                                    <input id="name" type="text" class="form-control @error('name') is-invalid @enderror" name="name" value="{{ old('name') }}" required autocomplete="name" autofocus>

                                    @error('name')
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                    @enderror
                                </div>
                            </div>

                            <div class="form-group row mb-0">
                                <div class="col-md-6 offset-md-4">
                                    <button type="submit" class="btn btn-primary">
                                        {{ __('Create') }}
                                    </button>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/wallets/edit.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-8">
                <div class="card">
                    <div class="card-header">{{ __('Rename Wallet') }}</div>

                    <div class="card-body">
                        @if (session('status'))
                            <div class="alert alert-success" role="alert">
                                {{ session('status') }}
                            </div>
                        @endif
                        <form method="POST" action="{{ route('wallet.update', $wallet->id) }}">
                            @csrf
                            @method('PATCH')
                            <div class="form-group row">
                                <label for="name" class="col-md-4 col-form-label text-md-right">{{ __('Name') }}</label>

                                <div class="col-md-6">
                                    <input id="name" type="text" class="form-control @error('name') is-invalid @enderror" name="name" value="{{ $wallet->name }}" required autocomplete="name" autofocus>

                                    @error('name')
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                    @enderror
                                </div>
                            </div>

                            <div class="form-group row mb-0">
                                <div class="col-md-6 offset-md-4">
                                    <button type="submit" class="btn btn-primary">
                                        {{ __('Rename') }}
                                    </button>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/wallets/show.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12">
                <div class="card">
                    <div class="card-header">{{ $wallet->name }}</div>

                    <div class="card-body">
                        @if (session('status'))
                            <div class="alert alert-success" role="alert">
                                {{ session('status') }}
                            </div>
                        @endif

                        <h3>Transactions <a href="{{ route('transaction.create') }}" class="label label-default">{{ __('Add new') }}</a></h3>

                            <table class="table">
                                <thead>
                                <tr>
                                    <th scope="row">Total</th>
                                    <th scope="row">Deposits</th>
                                    <th scope="row">{{ $wallet->sumDeposits }}</th>
                                    <th scope="row">Withdrawals</th>
                                    <th scope="row">{{ $wallet->sumWithdrawals }}</th>
                                    <th></th>
                                    <th scope="row">Balance</th>
                                    <th scope="row">{{ $wallet->sumTransactions }}</th>
                                </tr>
                                <tr>
                                    <th scope="col">Transaction ID</th>
                                    <th scope="col">Date</th>
                                    <th scope="col">FROM</th>
                                    <th scope="col">TO</th>
                                    <th scope="col">Amount</th>
                                    <th scope="col">Reference</th>
                                    <th scope="col">Fraudulent</th>
                                    <th scope="col">Delete</th>
                                </tr>
                                </thead>
                                <tbody>
                                @forelse($wallet->transactions as $transaction)
                                    <tr>
                                        <th scope="row">#{{ $transaction->id }}</th>
                                        <td>{{ $transaction->created_at }}</td>
                                        <td>{{ $transaction->from->name }}</td>
                                        <td>{{ $transaction->to->name }}</td>
                                        <td>{{ $transaction->amount }}</td>
                                        <td>{{ $transaction->reference }}</td>
                                        <td>
                                            {{ $transaction->fraud }}
                                            @if(!$transaction->fraud)
                                                <form method="POST" action="{{ route('transaction.update', $transaction->id) }}">
                                                    @csrf
                                                    @method('PATCH')
                                                    <input type="hidden" value="1" name="fraud">
                                                    <button type="submit" class="btn btn-primary">
                                                        {{ __('Mark') }}
                                                    </button>
                                                </form>
                                            @endif
                                        </td>
                                        <td>
                                            <form action="{{ route('transaction.destroy', $transaction->id)}}" method="post">
                                                @csrf
                                                @method('DELETE')
                                                <button class="btn btn-danger" type="submit">{{ __('Delete') }}</button>
                                            </form>
                                        </td>
                                    </tr>
                                @empty
                                    <tr>
                                        <th scope="row">You</th>
                                        <td>do</td>
                                        <td>not</td>
                                        <td>have</td>
                                        <td>any</td>
                                        <td>transactions</td>
                                    </tr>
                                @endforelse
                                </tbody>
                            </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection